# Generated by Django 5.2.9 on 2025-12-06 05:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(editable=False, max_length=10, unique=True)),
                ('ticker', models.CharField(default='', max_length=10)),
                ('first_txn', models.DateField(blank=True, null=True)),
                ('last_txn', models.DateField(blank=True, null=True)),
                ('exchange', models.CharField(choices=[('ASX', 'ASX'), ('PSX', 'PSX')], default='ASX', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=250)),
                ('total_investment', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('currency', models.CharField(default='AUD', max_length=5)),
                ('plateform', models.CharField(default='STAKE', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='', max_length=5)),
                ('plateform', models.CharField(default='STAKE', max_length=10)),
                ('total_amount', models.FloatField(default=0)),
                ('date_transaction', models.DateField(default=datetime.date.today)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='AppSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Gmail', 'Gmail'), ('API', 'API')], max_length=100)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_symbol', models.CharField(default='', max_length=25)),
                ('company_name', models.CharField(max_length=100)),
                ('sector', models.CharField(default='', max_length=50)),
                ('Exchange', models.CharField(default='ASX', max_length=100)),
                ('number_of_shares', models.IntegerField(default=0)),
                ('investment_amount', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('average_buy_price', models.FloatField(default=0)),
                ('Realized_PnL', models.FloatField(default=0)),
                ('UnRealized_PnL', models.FloatField(default=0)),
                ('LTP', models.FloatField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=25)),
                ('date_transaction', models.DateField(default=datetime.date.today)),
                ('Buy_Price', models.FloatField(default=0)),
                ('Quantity', models.FloatField(default=0)),
                ('Total', models.FloatField(default=0)),
                ('transaction_type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Dividend Reinvestment', 'RDP'), ('Cash Deposit', 'CD'), ('Dividend Deposit', 'Dividend')], max_length=50)),
                ('Commission', models.FloatField(default=0)),
                ('Holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.stockholding')),
            ],
        ),
        migrations.CreateModel(
            name='TickerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='dashboard.ticker')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
