# Generated by Django 5.2.9 on 2025-12-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRefreshState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_refresh', models.DateTimeField(blank=True, null=True)),
                ('refresh_lock_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('refresh_lock_acquired_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_lock_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
