# Generated by Django 5.2.9 on 2025-12-20 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_marketrefreshstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='plateform',
            new_name='platform',
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_portfolio_per_user_name'),
        ),
    ]
